import { readFileSync } from "node:fs";
import { describe, expect, it } from "vitest";

describe("overlay smoke", () => {
  it("public UI copy cannot imply arming always works", () => {
    const vue = readFileSync("src/renderer/App.vue", "utf8");
    expect(vue).toContain("dry-run-switch");
    expect(vue).toContain("E-stop ready · Ctrl+Shift+Esc");
    expect(vue).toContain("runtime.isNative.value");
    expect(vue).toContain("<RouterView");
    expect(vue).toContain("Tools &amp; QA");
    expect(vue).toContain("GameActionRail");
    const rail = readFileSync("src/renderer/components/GameActionRail.vue", "utf8");
    expect(rail).toContain("Empty");
    expect(rail).toContain("Fill");
    expect(rail).toContain("2-cycle");
    expect(rail).toContain("Sort");
    expect(rail).toContain("Dry-run");
    expect(rail).toContain("Fix in Cursor");
    expect(rail).not.toContain("Listen once");
    const cal = readFileSync("src/renderer/CalibrationPanel.vue", "utf8");
    expect(cal).toContain("Screenshot");
    expect(cal).toContain("Look");
    expect(cal).toContain("Reset");
    expect(cal).toContain("Vendor");
    expect(cal).toContain("Search");
    expect(cal).not.toContain("Stash open");
    expect(cal).not.toContain("Bag open");
    expect(cal).not.toContain("Find STASH nameplates");
    expect(cal).not.toContain("Walk to");
    expect(cal).not.toContain("New screenshot for quad stash");
    expect(cal).toContain("mapsCalibrationHidesOthers");
    expect(cal).toContain("juiceCalibrationFocus");
    expect(cal).toContain('v-if="diagnostic && !mapsSolo"');
    expect(cal).toContain("Maps: other marks hidden");
    expect(cal).toContain("Show on game");
    expect(cal).toContain("Ctrl+Alt+G");
    expect(cal).toContain("Nudge Maps");
    expect(cal).toContain("nudgeMaps(-8, 0)");
    expect(cal).toContain("juice-grids");
    expect(cal).toContain("gridClickCenters");
    expect(cal).toContain("class=\"box grid lattice maps\"");
    expect(cal).toContain("see-through");
    const calCss = readFileSync("src/renderer/styles.css", "utf8");
    expect(calCss).toContain(".box.lattice");
    expect(calCss).toContain("background-color: transparent");
    expect(calCss).toContain("linear-gradient(to right, currentColor 1px, transparent 1px)");
    expect(calCss).not.toContain("repeating-linear-gradient(to right, currentColor 0 1px");
    expect(calCss).toContain(".grid-dot.maps { background: transparent");
    const overlay = readFileSync("src/main/gridOverlayWindow.ts", "utf8");
    expect(overlay).toContain("Juice grid overlay — no game input");
    expect(overlay).toContain("renderJuiceGridOverlay");
    expect(overlay).toContain("Pink = Maps 12×8 wells");
    expect(overlay).toContain("Ctrl+Alt+G toggles this overlay");
    const transfers = readFileSync("src/renderer/TransferPanel.vue", "utf8");
    expect(transfers).toContain("Dry-run / preview (zero input)");
    expect(transfers).toContain("Right — detection is correct");
    expect(transfers).toContain("Wrong — detection is incorrect");
    const dryRun = readFileSync("src/main/dryRunOverlayWindow.ts", "utf8");
    expect(dryRun).toContain("Each outline is one detected item");
    expect(dryRun).toContain("Shift-click adds more");
    expect(dryRun).toContain("Right — detection is correct");
    expect(dryRun).toContain("Fix in Cursor");
    expect(dryRun).not.toContain("click-through overlay");
  });
});
