/** Stable public command catalog. No arbitrary IPC names, script paths or shell arguments. */
export const DECK_ACTIONS = [
  ["rings.gamble", "Gamble rings", "RINGS", "One bounded batch at Ange using the existing ring policy."],
  ["rings.cleanup", "Clean up rings", "CLEAN", "Rescan and sell ring rejects; buys nothing."],
  ["bag.workflow", "Identify & drop", "ID DROP", "Verified identification and low-priority drops."],
  ["transfer.empty", "Empty inventory", "EMPTY", "Deposit inventory into stash."],
  ["transfer.fill", "Fill inventory", "FILL", "Withdraw from the selected stash tab."],
  ["transfer.two-cycle", "Two-cycle transfer", "2 CYCLE", "Existing two-cycle transfer."],
  ["sort.preview", "Preview stash sort", "PLAN", "Scan and prepare a stash sort plan."],
  ["sort.execute", "Execute stash sort", "SORT", "Execute the current validated plan."],
  ["script.sort-gear", "Sort gear", "GEAR", "Route gear using the existing sorter."],
  ["script.sort-inventory", "Sort inventory by class", "CLASS SORT", "Use the same class-routed inventory sorter as the Sort hotkey."],
  ["script.craft-gear", "Craft gear", "CRAFT", "Use the existing crafting planner and interlocks."],
  ["script.shop-scan", "Scan shop", "SHOP SCAN", "Scan shop and reconcile listings."],
  ["script.shop-buckets", "List inventory", "LIST", "Price and list inventory in merchant buckets."],
  ["script.shop-list", "List shop items", "SHOP LIST", "Existing shop listing operation."],
  ["script.shop-apply", "Reprice shop", "REPRICE", "Apply the existing repricing plan."],
  ["script.shop-apply-step", "Reprice step mode", "STEP PRICE", "Reprice with existing teaching controls."],
  ["script.vendor-cycle", "Vendor cycle", "VENDOR", "Existing hideout, vendor and return workflow."],
  ["combat.start", "Start combat assist", "COMBAT", "Start saved combat configuration."],
  ["combat.pause", "Pause combat assist", "PAUSE", "Stop combat, preserving configuration (F8 semantics)."],
  ["combat.resume", "Resume combat assist", "RESUME", "Explicitly restart saved combat configuration."],
  ["combat.stop", "Stop combat assist", "END FIGHT", "Stop generated combat input."],
  ["combat.health", "Health flask control", "HEALTH", "Toggle health automation setting; does not directly drink a flask."],
  ["combat.mana", "Mana flask control", "MANA", "Toggle mana automation setting; preserves physical-trigger semantics."],
  ["combat.unleash", "Unleash control", "UNLEASH", "Toggle Unleash configuration, preserving its trigger."],
  ["combat.sigilSequence", "Sigil sequence control", "SIGIL", "Toggle the existing sequence; validation requires both skill modules."],
  ["combat.verisium", "Verisium control", "VERISIUM", "Toggle Verisium configuration; does not synthesize a trigger."],
  ["voice.listen", "Listen for transfer", "LISTEN", "Listen once using saved voice settings."],
  ["voice.cancel", "Cancel voice transfer", "MUTE", "Cancel recognition and its transfer."],
  ["helper.start", "Start price helper", "PRICES", "Start calibrated price overlay."],
  ["helper.stop", "Stop price helper", "HIDE PRICE", "Stop price overlay scanning."],
  ["helper.refresh", "Refresh helper prices", "REFRESH", "Refresh helper market data."],
  ["helper.refreshRumours", "Refresh rumours", "RUMOURS", "Refresh community rumour data."],
  ["helper.calibrate", "Calibrate price helper", "PRICE CAL", "Start the existing helper calibration flow."],
  ["helper.debug", "Price helper debug", "DEBUG", "Toggle overlay debug labels."],
  ["helper.prices", "Price helper price mode", "PRICE MODE", "Select price mode; explicitly start scanning afterwards."],
  ["helper.rumours", "Price helper rumour mode", "RUMOUR MODE", "Select Island Rumours mode; explicitly start scanning afterwards."],
  ["tabs.survey", "Survey stash tabs", "SURVEY", "Run the existing visible tab survey."],
  ["item.evaluate", "Evaluate clipboard item", "EVALUATE", "Evaluate copied item text with the app evaluator."],
  ["scan.inventory", "Scan inventory", "BAG SCAN", "Run the calibrated inventory scanner."],
  ["scan.stash-normal", "Scan normal stash", "12 SCAN", "Run the normal stash scanner."],
  ["scan.stash-quad", "Scan quad stash", "24 SCAN", "Run the quad stash scanner."],
  ["bag.capture", "Capture bag", "CAPTURE", "Capture a new bag session."],
  ["bag.identify", "Identify one item", "ID ONE", "Identify one item in the selected bag session."],
  ["bag.drop", "Drop one reject", "DROP ONE", "Verify and drop one low-priority item."],
  ["bag.reconcile", "Reconcile bag", "RECHECK", "Reconcile the saved bag action."],
  ["script.value-dump", "Value stash", "VALUE", "Capture and value stash items."],
  ["script.value-dump-resume", "Resume stash pricing", "VALUE NEXT", "Resume pending prices from the saved report."],
  ["script.value-dump-capture-resume", "Resume stash capture", "SCAN NEXT", "Resume the saved stash capture."],
  ["script.value-dump-sort", "Sort valued stash", "VALUE SORT", "Move using the existing valuation report."],
  ["valuation.reassess", "Reassess saved stash", "REASSESS", "Re-evaluate the saved report without moving items."],
  ["feed.refresh", "Refresh market feed", "MARKET", "Refresh the app price feed."],
  ["script.renumber", "Renumber stash tabs", "NUMBER", "Existing tab renumber operation."],
  ["script.finish-gear", "Finish gear tabs", "GEAR TABS", "Existing gear-tab finishing operation."],
  ["script.juice-maps", "Juice T15 maps", "JUICE T15", "Alch weak maps, exalt keepers, and Vaal every 6-mod T15 on the open stash tab."],
  ["overlay.hide", "Hide dry-run overlay", "HIDE", "Dismiss the current preview overlay."],
  ["workflow.stop", "Stop current workflow", "STOP", "Cancel app workflows without rearming anything."],
  ["safety.estop", "Emergency stop", "E STOP", "Latch the global input kill switch and cancel all app workflows."],
  ["safety.rearm", "Rearm input", "REARM", "Explicitly rearm the stopped app; starts no workflow."],
  ["safety.dry-on", "Enable dry-run", "DRY ON", "Enable shared dry-run preference."],
  ["safety.dry-off", "Disable dry-run", "LIVE", "Explicitly enable live execution; starts no workflow."],
  ["open.dashboard", "Open dashboard", "HOME", "Open dashboard only."],
  ["open.calibration", "Open calibration", "CALIBRATE", "Open calibration settings only."],
  ["open.bag-triage", "Open bag tools", "BAG TOOLS", "Open bag tools only."],
  ["open.shop", "Open shop", "SHOP", "Open shop settings only."],
  ["open.settings", "Open settings", "SETTINGS", "Open automation defaults only."],
  ["open.combat", "Open combat settings", "FIGHT CFG", "Open flask and skill settings only."],
  ["open.price-helper", "Open price helper", "PRICE CFG", "Open price helper settings only."],
  ["open.transfers", "Open transfers", "TRANSFER", "Open transfer settings only."],
  ["open.stash-tabs", "Open stash tabs", "TAB CFG", "Open tab survey and plan tools only."],
  ["open.items", "Open item log", "ITEM LOG", "Open catalog and scan history."],
  ["open.search", "Open search and rules", "RULES", "Open query and rule editors."],
  ["open.builds", "Open builds", "BUILDS", "Open build profile editor."],
  ["open.filter", "Open loot filter", "FILTER", "Open filter generation settings."],
  ["open.diagnostics", "Open replay tools", "REPLAY", "Open replay and diagnostics."],
  ["open.hotkeys", "Open hotkeys", "HOTKEYS", "Open hotkey assignment settings."],
  ["open.sort-stash", "Open stash sort", "SORT CFG", "Open stash sort preview and plan tools."],
] as const;
export type DeckActionId = typeof DECK_ACTIONS[number][0];
export type DeckVisualState = "idle" | "active" | "paused" | "unavailable" | "error" | "disconnected";
export interface DeckButtonState { state: DeckVisualState; detail: string; count?: number }
export interface DeckStatus { version: 1; session: string; dryRun: boolean; killLatched: boolean; buttons: Record<DeckActionId, DeckButtonState> }
export interface DeckCommand { version: 1; id: string; session: string; action: DeckActionId; parameters: Record<string, never> }
export interface DeckAck { id: string; ok: boolean; phase: "accepted" | "completed" | "rejected"; reason: string }
export const isDeckAction = (id: unknown): id is DeckActionId => DECK_ACTIONS.some(a => a[0] === id);
export interface DeckPreferences { dryRun: boolean; allowlist: string[]; transferActionsPerMinute: number; sortActionsPerMinute: number }
export interface DeckBridge {
  preferences(value: DeckPreferences): Promise<void>;
  onDryRun(callback: (enabled: boolean) => void): () => void;
  onNavigate(callback: (route: string) => void): () => void;
}
